// <auto-generated />
using GraphQL.Privacy.Sample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQL.Privacy.Sample.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("GraphQL.Privacy.Sample.Models.Album", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsHidden");

                    b.Property<string>("Title");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsHidden = false,
                            Title = "Album 1",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            IsHidden = false,
                            Title = "Album 2",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            IsHidden = false,
                            Title = "Album 3",
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            IsHidden = false,
                            Title = "Album 4",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            IsHidden = true,
                            Title = "Album 5",
                            UserId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            IsHidden = false,
                            Title = "Album 6",
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("GraphQL.Privacy.Sample.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "User1"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "User2"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "User3"
                        });
                });

            modelBuilder.Entity("GraphQL.Privacy.Sample.Models.Album", b =>
                {
                    b.HasOne("GraphQL.Privacy.Sample.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
